# Classification of Head and neck cancer samples as cancerous (tumor) and non cancerous (normal) based on methylation data

In [1]:
import numpy as np
import pandas as pd

Read the cancer data into Pandas dataframe (Data is already split into x_train, y_train, x_test and y_test)

In [2]:
data = pd.read_csv("/home/seeraja/anaconda3/iitgn/datasets-master/cancer subtype classification datasetspart01/head_neck_2/methylation/methyl_x_train.csv", low_memory=False)

In [3]:
data

Unnamed: 0          Idx    AAAS-M    AACS-M   AADAT-M   AAED1-M  \
0            28  C3N-03490-N  0.032548  0.019644  0.031529  0.026623   
1            99    C3N-04276  0.026822  0.015984  0.016237  0.022432   
2            23    C3N-00498  0.023308  0.014592  0.080124  0.024676   
3            33    C3N-01620  0.023346  0.014332  0.021047  0.022531   
4            86    C3N-03785  0.029347  0.015822  0.017042  0.025958   
..          ...          ...       ...       ...       ...       ...   
110          21  C3N-02925-N  0.029961  0.017323  0.012091  0.022243   
111          33  C3N-03878-N  0.037367  0.025722  0.065418  0.028280   
112          18    C3N-00297  0.027386  0.016685  0.073422  0.021369   
113          34  C3N-03888-N  0.029970  0.018168  0.017234  0.028162   
114          12  C3N-01754-N  0.028356  0.017578  0.014578  0.022787   

      AAGAB-M    AAK1-M   AAMDC-M    AAMP-M  ...  ZSWIM7-M  ZSWIM8-M  \
0    0.023774  0.022213  0.021022  0.024074  ...  0.052558  0.016148   
1    0.021905  0.019470  0.024963  0.021150  ...  0.060409  0.013859   
2    0.019475  0.022044  0.022564  0.019460  ...  0.067604  0.012299   
3    0.019249  0.022003  0.014218  0.021051  ...  0.040795  0.010592   
4    0.017184  0.020531  0.019615  0.020664  ...  0.035241  0.015076   
..        ...       ...       ...       ...  ...       ...       ...   
110  0.021372  0.022003  0.019497  0.021648  ...  0.041921  0.016293   
111  0.022520  0.028332  0.029827  0.022756  ...  0.052322  0.018835   
112  0.024767  0.024152  0.022124  0.022584  ...  0.043808  0.014066   
113  0.026124  0.022844  0.022871  0.022608  ...  0.051360  0.014977   
114  0.020774  0.020728  0.018687  0.020901  ...  0.034896  0.015195   

       ZW10-M   ZWINT-M    ZXDC-M  ZYG11A-M  ZYG11B-M     ZYX-M   ZZEF1-M  \
0    0.020244  0.034220  0.030853  0.016933  0.145074  0.023474  0.020991   
1    0.022262  0.032040  0.036064  0.328353  0.021171  0.018502  0.020986   
2    0.020851  0.038137  0.064035  0.018555  0.060874  0.016466  0.021761   
3    0.020974  0.035922  0.025646  0.298594  0.096735  0.014568  0.022528   
4    0.021337  0.032470  0.021827  0.012323  0.014445  0.017886  0.018822   
..        ...       ...       ...       ...       ...       ...       ...   
110  0.018935  0.028977  0.026288  0.014124  0.058720  0.015568  0.018142   
111  0.022897  0.037415  0.031051  0.020243  0.082134  0.022863  0.022130   
112  0.027487  0.038417  0.040538  0.024058  0.020451  0.025344  0.023935   
113  0.021208  0.031242  0.023896  0.013649  0.077867  0.019447  0.020155   
114  0.020938  0.035260  0.025985  0.014649  0.014206  0.018669  0.019855   

       ZZZ3-M  
0    0.023185  
1    0.027803  
2    0.030849  
3    0.024099  
4    0.024582  
..        ...  
110  0.024336  
111  0.033970  
112  0.034050  
113  0.029925  
114  0.025870  

[115 rows x 13118 columns]

In [4]:
data2=data.drop(columns=["Unnamed: 0"])

In [5]:
data3=data2.drop(columns=["Idx"])

In [6]:
data3

AAAS-M    AACS-M   AADAT-M   AAED1-M   AAGAB-M    AAK1-M   AAMDC-M  \
0    0.032548  0.019644  0.031529  0.026623  0.023774  0.022213  0.021022   
1    0.026822  0.015984  0.016237  0.022432  0.021905  0.019470  0.024963   
2    0.023308  0.014592  0.080124  0.024676  0.019475  0.022044  0.022564   
3    0.023346  0.014332  0.021047  0.022531  0.019249  0.022003  0.014218   
4    0.029347  0.015822  0.017042  0.025958  0.017184  0.020531  0.019615   
..        ...       ...       ...       ...       ...       ...       ...   
110  0.029961  0.017323  0.012091  0.022243  0.021372  0.022003  0.019497   
111  0.037367  0.025722  0.065418  0.028280  0.022520  0.028332  0.029827   
112  0.027386  0.016685  0.073422  0.021369  0.024767  0.024152  0.022124   
113  0.029970  0.018168  0.017234  0.028162  0.026124  0.022844  0.022871   
114  0.028356  0.017578  0.014578  0.022787  0.020774  0.020728  0.018687   

       AAMP-M   AANAT-M    AAR2-M  ...  ZSWIM7-M  ZSWIM8-M    ZW10-M  \
0    0.024074  0.022467  0.015985  ...  0.052558  0.016148  0.020244   
1    0.021150  0.014992  0.018018  ...  0.060409  0.013859  0.022262   
2    0.019460  0.016609  0.014199  ...  0.067604  0.012299  0.020851   
3    0.021051  0.012886  0.010666  ...  0.040795  0.010592  0.020974   
4    0.020664  0.019219  0.012792  ...  0.035241  0.015076  0.021337   
..        ...       ...       ...  ...       ...       ...       ...   
110  0.021648  0.024316  0.017585  ...  0.041921  0.016293  0.018935   
111  0.022756  0.023088  0.034573  ...  0.052322  0.018835  0.022897   
112  0.022584  0.017363  0.017955  ...  0.043808  0.014066  0.027487   
113  0.022608  0.020652  0.015272  ...  0.051360  0.014977  0.021208   
114  0.020901  0.017580  0.012256  ...  0.034896  0.015195  0.020938   

      ZWINT-M    ZXDC-M  ZYG11A-M  ZYG11B-M     ZYX-M   ZZEF1-M    ZZZ3-M  
0    0.034220  0.030853  0.016933  0.145074  0.023474  0.020991  0.023185  
1    0.032040  0.036064  0.328353  0.021171  0.018502  0.020986  0.027803  
2    0.038137  0.064035  0.018555  0.060874  0.016466  0.021761  0.030849  
3    0.035922  0.025646  0.298594  0.096735  0.014568  0.022528  0.024099  
4    0.032470  0.021827  0.012323  0.014445  0.017886  0.018822  0.024582  
..        ...       ...       ...       ...       ...       ...       ...  
110  0.028977  0.026288  0.014124  0.058720  0.015568  0.018142  0.024336  
111  0.037415  0.031051  0.020243  0.082134  0.022863  0.022130  0.033970  
112  0.038417  0.040538  0.024058  0.020451  0.025344  0.023935  0.034050  
113  0.031242  0.023896  0.013649  0.077867  0.019447  0.020155  0.029925  
114  0.035260  0.025985  0.014649  0.014206  0.018669  0.019855  0.025870  

[115 rows x 13116 columns]

Getting the labels

In [7]:
data_y = pd.read_csv("/home/seeraja/anaconda3/iitgn/datasets-master/cancer subtype classification datasetspart01/head_neck_2/methylation/methyl_y_train.csv", low_memory=False)

In [8]:
data_y

Unnamed: 0   0
0             0  NC
1             1   C
2             2   C
3             3   C
4             4   C
..          ...  ..
110         110  NC
111         111  NC
112         112   C
113         113  NC
114         114  NC

[115 rows x 2 columns]

Convert to numpy array

In [9]:
arr_y=data_y.values

In [10]:
arr_y[:,1]

array(['NC', 'C', 'C', 'C', 'C', 'NC', 'C', 'NC', 'NC', 'C', 'C', 'C',
       'C', 'C', 'C', 'C', 'C', 'NC', 'C', 'C', 'NC', 'C', 'C', 'C', 'NC',
       'C', 'C', 'C', 'C', 'NC', 'C', 'C', 'C', 'C', 'NC', 'C', 'C', 'C',
       'NC', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'NC', 'C', 'C', 'NC', 'C',
       'C', 'C', 'C', 'C', 'NC', 'NC', 'C', 'C', 'C', 'C', 'NC', 'C',
       'NC', 'C', 'NC', 'C', 'C', 'C', 'C', 'C', 'C', 'NC', 'C', 'NC',
       'NC', 'C', 'C', 'C', 'C', 'NC', 'C', 'C', 'C', 'C', 'C', 'NC', 'C',
       'C', 'C', 'C', 'C', 'C', 'NC', 'NC', 'C', 'C', 'C', 'C', 'C', 'C',
       'C', 'NC', 'C', 'C', 'NC', 'C', 'NC', 'C', 'NC', 'NC', 'NC', 'C',
       'NC', 'NC'], dtype=object)

In [12]:
y=arr_y[:,1]

In [13]:
y

array(['NC', 'C', 'C', 'C', 'C', 'NC', 'C', 'NC', 'NC', 'C', 'C', 'C',
       'C', 'C', 'C', 'C', 'C', 'NC', 'C', 'C', 'NC', 'C', 'C', 'C', 'NC',
       'C', 'C', 'C', 'C', 'NC', 'C', 'C', 'C', 'C', 'NC', 'C', 'C', 'C',
       'NC', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'NC', 'C', 'C', 'NC', 'C',
       'C', 'C', 'C', 'C', 'NC', 'NC', 'C', 'C', 'C', 'C', 'NC', 'C',
       'NC', 'C', 'NC', 'C', 'C', 'C', 'C', 'C', 'C', 'NC', 'C', 'NC',
       'NC', 'C', 'C', 'C', 'C', 'NC', 'C', 'C', 'C', 'C', 'C', 'NC', 'C',
       'C', 'C', 'C', 'C', 'C', 'NC', 'NC', 'C', 'C', 'C', 'C', 'C', 'C',
       'C', 'NC', 'C', 'C', 'NC', 'C', 'NC', 'C', 'NC', 'NC', 'NC', 'C',
       'NC', 'NC'], dtype=object)

# Using PCA for dimensionality reduction

Import PCA 

In [14]:
from sklearn.decomposition import PCA

In [15]:
data3.shape

(115, 13116)

Fit and transform the data and find out how many principal components are required to capture 85% of the data

In [16]:
pca = PCA()
x_train = pca.fit_transform(data3)

In [17]:
x_train

array([[-5.54523301e+00, -2.02593265e-01, -1.78900244e-01, ...,
        -3.65713617e-01, -5.64283881e-01,  2.50566606e-15],
       [ 8.29493706e+00, -1.30885509e+00,  6.28871638e-01, ...,
        -1.34692608e-03,  1.63312346e-03,  2.50566606e-15],
       [ 1.83666130e+00, -1.17976055e+00,  1.46011935e+00, ...,
        -8.14539468e-03,  2.64219367e-03,  2.50566606e-15],
       ...,
       [ 3.87790599e+00, -8.66311278e-01, -1.75660231e-01, ...,
         1.34466553e-04, -4.61138002e-03,  2.50566606e-15],
       [-5.30606893e+00, -4.27099706e-01,  1.21050798e-01, ...,
        -2.62954684e-01, -7.21353287e-02,  2.50566606e-15],
       [-5.00799548e+00, -3.74692930e-01,  1.94942768e-01, ...,
         6.04624993e-02,  9.74911379e-02,  2.50566606e-15]])

Get the explained variance

In [18]:
explained_variance = pca.explained_variance_
explained_variance

array([1.13284901e+01, 3.89539067e+00, 2.85783336e+00, 1.98680133e+00,
       1.37810581e+00, 1.10788717e+00, 1.02154536e+00, 7.70955447e-01,
       6.91983237e-01, 6.42917029e-01, 6.17156022e-01, 5.56238922e-01,
       5.05108409e-01, 4.85567308e-01, 4.59643835e-01, 4.27205002e-01,
       4.18049059e-01, 3.85560039e-01, 3.79111145e-01, 3.65852796e-01,
       3.41703190e-01, 3.37674574e-01, 3.32519466e-01, 3.25142423e-01,
       3.11918425e-01, 3.04436402e-01, 2.83375843e-01, 2.75823633e-01,
       2.63144328e-01, 2.61726651e-01, 2.56247483e-01, 2.52881967e-01,
       2.39229462e-01, 2.33227002e-01, 2.29981791e-01, 2.21316619e-01,
       2.10940185e-01, 1.98718331e-01, 1.96800110e-01, 1.90876523e-01,
       1.87599314e-01, 1.83554369e-01, 1.81612592e-01, 1.77561146e-01,
       1.76577569e-01, 1.67955252e-01, 1.65569675e-01, 1.60551894e-01,
       1.59344429e-01, 1.55601945e-01, 1.49971819e-01, 1.47212536e-01,
       1.46715263e-01, 1.42530160e-01, 1.39939966e-01, 1.35349531e-01,
      

In [19]:
explained_variance.size

115

Get the explained variance ratio to check how much information each principal component contributes

In [20]:
explained_variance_ratio = pca.explained_variance_ratio_
explained_variance_ratio

array([2.73482118e-01, 9.40389834e-02, 6.89912172e-02, 4.79635530e-02,
       3.32689787e-02, 2.67456058e-02, 2.46612202e-02, 1.86117061e-02,
       1.67052308e-02, 1.55207189e-02, 1.48988201e-02, 1.34282148e-02,
       1.21938684e-02, 1.17221249e-02, 1.10963040e-02, 1.03131951e-02,
       1.00921607e-02, 9.30784025e-03, 9.15215690e-03, 8.83208589e-03,
       8.24908804e-03, 8.15183286e-03, 8.02738291e-03, 7.84929304e-03,
       7.53005130e-03, 7.34942709e-03, 6.84100220e-03, 6.65868361e-03,
       6.35259135e-03, 6.31836709e-03, 6.18609399e-03, 6.10484674e-03,
       5.77526038e-03, 5.63035444e-03, 5.55201150e-03, 5.34282478e-03,
       5.09232635e-03, 4.79727746e-03, 4.75096949e-03, 4.60796764e-03,
       4.52885223e-03, 4.43120285e-03, 4.38432624e-03, 4.28651991e-03,
       4.26277528e-03, 4.05462314e-03, 3.99703271e-03, 3.87589800e-03,
       3.84674848e-03, 3.75640081e-03, 3.62048343e-03, 3.55387133e-03,
       3.54186662e-03, 3.44083365e-03, 3.37830354e-03, 3.26748543e-03,
      

Convert to percentage and check how much information is captured by first 40 principal components

In [22]:
percentage=np.cumsum(explained_variance_ratio)
percentage[40]

0.8627226078222313

Selecting first 39 principal components as they capture 85% of the information

In [35]:
percentage[39]

0.8581937555884175

In [31]:
percentage

array([0.27348212, 0.3675211 , 0.43651232, 0.48447587, 0.51774485,
       0.54449046, 0.56915168, 0.58776338, 0.60446861, 0.61998933,
       0.63488815, 0.64831637, 0.66051024, 0.67223236, 0.68332866,
       0.69364186, 0.70373402, 0.71304186, 0.72219402, 0.7310261 ,
       0.73927519, 0.74742702, 0.75545441, 0.7633037 , 0.77083375,
       0.77818318, 0.78502418, 0.79168286, 0.79803546, 0.80435382,
       0.81053992, 0.81664476, 0.82242002, 0.82805038, 0.83360239,
       0.83894521, 0.84403754, 0.84883482, 0.85358579, 0.85819376,
       0.86272261, 0.86715381, 0.87153814, 0.87582466, 0.88008743,
       0.88414206, 0.88813909, 0.89201499, 0.89586173, 0.89961814,
       0.90323862, 0.90679249, 0.91033436, 0.91377519, 0.91715349,
       0.92042098, 0.92366696, 0.92681305, 0.92970556, 0.93247739,
       0.93518604, 0.93780032, 0.94037865, 0.94290988, 0.94536138,
       0.94775801, 0.95013409, 0.95244399, 0.95469768, 0.95691301,
       0.95906102, 0.96117834, 0.96321801, 0.9651985 , 0.96712

Using first 39 principal components to fit and transform the data

In [36]:
pca_39 = PCA(n_components=39)
x_train_39 = pca_39.fit_transform(data3)

In [37]:
x_train_39

array([[-5.54523301, -0.20259321, -0.17890048, ...,  0.0790327 ,
         0.10607207,  0.06084006],
       [ 8.29493706, -1.30885511,  0.62887179, ..., -0.01132444,
         0.07842955,  0.07192682],
       [ 1.8366613 , -1.17976048,  1.46011854, ...,  1.95262212,
         0.32292762,  1.7150537 ],
       ...,
       [ 3.87790599, -0.86631051, -0.17565927, ...,  0.23802414,
         0.18053228,  0.24630601],
       [-5.30606893, -0.42709969,  0.12105119, ..., -0.05408139,
        -0.0693448 , -0.24273327],
       [-5.00799548, -0.37469306,  0.19494278, ...,  0.01038169,
         0.03302596, -0.03753971]])

In [38]:
x_train_39.shape

(115, 39)

# Using Random forest for classifier

Create the grid for RandomizedSearchCV

In [39]:
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [100,200,500,1000, 1500]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [5,10,15,20,30,40,50,70]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]

# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

In [40]:
random_grid

{'n_estimators': [100, 200, 500, 1000, 1500],
 'max_features': ['auto', 'sqrt'],
 'max_depth': [5, 10, 15, 20, 30, 40, 50, 70, None],
 'min_samples_split': [2, 5, 10],
 'min_samples_leaf': [1, 2, 4],
 'bootstrap': [True, False]}

Using Random forest classifier

In [41]:
# Use the random grid to search for best hyperparameters
# First create the base model to tune
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random_39 = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=42, n_jobs = -1)# Fit the random search model
rf_random_39.fit(x_train_39, y)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': [5, 10, 15, 20, 30, 40, 50,
                                                      70, None],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [100, 200, 500, 1000,
                                                         1500]},
                   random_state=42, verbose=2)

Get the best parameters

In [42]:
rf_random_39.best_params_

{'n_estimators': 100,
 'min_samples_split': 2,
 'min_samples_leaf': 2,
 'max_features': 'sqrt',
 'max_depth': 15,
 'bootstrap': False}

Get the best score

In [43]:
rf_random_39.best_score_

0.9739091318038686

Get the best model

In [44]:
best_random_39 = rf_random_39.best_estimator_

Testing on test data

In [47]:
data_test = pd.read_csv("/home/seeraja/anaconda3/iitgn/datasets-master/cancer subtype classification datasetspart01/head_neck_2/methylation/methyl_x_test.csv", low_memory=False)

In [48]:
data_test

Unnamed: 0          Idx    AAAS-M    AACS-M   AADAT-M   AAED1-M   AAGAB-M  \
0            8    C3L-02621  0.037790  0.025241  0.178666  0.033382  0.022867   
1           32  C3N-03849-N  0.035954  0.020088  0.045332  0.027187  0.022098   
2           89    C3N-03849  0.032703  0.016203  0.027040  0.026563  0.021239   
3           84    C3N-03782  0.033023  0.022066  0.028099  0.031388  0.023885   
4            1  C3L-00977-N  0.032077  0.020039  0.038071  0.028240  0.021744   
5           37  C3N-03933-N  0.039013  0.024325  0.029937  0.030456  0.024886   
6           77    C3N-03488  0.032327  0.018929  0.014116  0.027540  0.022616   
7           32    C3N-01340  0.030459  0.020154  0.051160  0.027250  0.021616   
8           73    C3N-03456  0.029130  0.017175  0.016683  0.032308  0.020697   
9           17    C3N-00295  0.025283  0.021333  0.122123  0.038131  0.030067   
10          44    C3N-01944  0.038059  0.027857  0.029663  0.032365  0.022039   
11           2  C3L-00994-N  0.032656  0.019244  0.014974  0.023579  0.021551   
12          18  C3N-02333-N  0.039014  0.024294  0.057247  0.026583  0.023205   
13          45    C3N-01945  0.039678  0.021543  0.048419  0.030677  0.025495   
14          80    C3N-03619  0.022815  0.016332  0.091189  0.021174  0.020760   
15          14  C3N-01943-N  0.038782  0.022740  0.053748  0.032784  0.023910   
16          50    C3N-02279  0.035088  0.021293  0.029899  0.076390  0.034728   
17          51    C3N-02333  0.045204  0.025347  0.149807  0.030683  0.022987   
18          11  C3L-04354-N  0.036832  0.019571  0.121990  0.034316  0.024452   
19          34    C3N-01645  0.025058  0.022578  0.058160  0.031938  0.032731   
20          62    C3N-03009  0.036358  0.021602  0.035600  0.026769  0.026829   
21          48    C3N-01948  0.033066  0.021917  0.073770  0.024795  0.023653   
22          42    C3N-01859  0.030188  0.015932  0.059928  0.028772  0.020103   
23          25    C3N-00822  0.024628  0.020082  0.019431  0.034690  0.025649   
24           5  C3L-00999-N  0.025609  0.017521  0.027507  0.021475  0.019821   
25          49    C3N-02275  0.035175  0.022619  0.029059  0.034911  0.022575   
26          31    C3N-01338  0.033858  0.016167  0.027948  0.027826  0.037115   
27         103    C3N-04280  0.023329  0.018851  0.468201  0.023400  0.020598   
28          46    C3N-01946  0.029792  0.017583  0.312069  0.028452  0.021128   

      AAK1-M   AAMDC-M    AAMP-M  ...  ZSWIM7-M  ZSWIM8-M    ZW10-M   ZWINT-M  \
0   0.028465  0.028443  0.024042  ...  0.041304  0.022708  0.022526  0.031664   
1   0.020492  0.021237  0.024706  ...  0.064079  0.019310  0.019493  0.038318   
2   0.021962  0.019494  0.024251  ...  0.045012  0.017111  0.019312  0.032742   
3   0.024403  0.023604  0.022987  ...  0.059958  0.017567  0.023987  0.034412   
4   0.026103  0.025480  0.024198  ...  0.078680  0.015795  0.020623  0.035171   
5   0.025438  0.026905  0.029035  ...  0.076644  0.019317  0.022338  0.039114   
6   0.020843  0.032955  0.023811  ...  0.047215  0.016792  0.022037  0.030985   
7   0.023836  0.027062  0.024157  ...  0.055558  0.018560  0.018914  0.035771   
8   0.020779  0.019705  0.021389  ...  0.043577  0.013839  0.017720  0.030853   
9   0.024259  0.026528  0.022140  ...  0.066336  0.019058  0.023817  0.040214   
10  0.024392  0.027310  0.022695  ...  0.045010  0.017810  0.027443  0.027736   
11  0.024865  0.022333  0.026384  ...  0.048387  0.016792  0.023258  0.035888   
12  0.024560  0.022667  0.024647  ...  0.062805  0.016720  0.023837  0.030709   
13  0.024252  0.029137  0.024961  ...  0.069800  0.017848  0.024963  0.030404   
14  0.018938  0.023488  0.020284  ...  0.066908  0.015322  0.021015  0.028390   
15  0.026165  0.023987  0.028101  ...  0.058173  0.014560  0.022520  0.028825   
16  0.030013  0.028619  0.028134  ...  0.060952  0.018681  0.026286  0.053717   
17  0.025586  0.026777  0.027806  ...  0.067582  0.021383  0.023877  0.042046   
18  0.025074  0.025287  0.026112  

In [49]:
data_test2=data_test.drop(columns=["Unnamed: 0"])

In [50]:
data_test3=data_test2.drop(columns=["Idx"])

In [51]:
data_test3

AAAS-M    AACS-M   AADAT-M   AAED1-M   AAGAB-M    AAK1-M   AAMDC-M  \
0   0.037790  0.025241  0.178666  0.033382  0.022867  0.028465  0.028443   
1   0.035954  0.020088  0.045332  0.027187  0.022098  0.020492  0.021237   
2   0.032703  0.016203  0.027040  0.026563  0.021239  0.021962  0.019494   
3   0.033023  0.022066  0.028099  0.031388  0.023885  0.024403  0.023604   
4   0.032077  0.020039  0.038071  0.028240  0.021744  0.026103  0.025480   
5   0.039013  0.024325  0.029937  0.030456  0.024886  0.025438  0.026905   
6   0.032327  0.018929  0.014116  0.027540  0.022616  0.020843  0.032955   
7   0.030459  0.020154  0.051160  0.027250  0.021616  0.023836  0.027062   
8   0.029130  0.017175  0.016683  0.032308  0.020697  0.020779  0.019705   
9   0.025283  0.021333  0.122123  0.038131  0.030067  0.024259  0.026528   
10  0.038059  0.027857  0.029663  0.032365  0.022039  0.024392  0.027310   
11  0.032656  0.019244  0.014974  0.023579  0.021551  0.024865  0.022333   
12  0.039014  0.024294  0.057247  0.026583  0.023205  0.024560  0.022667   
13  0.039678  0.021543  0.048419  0.030677  0.025495  0.024252  0.029137   
14  0.022815  0.016332  0.091189  0.021174  0.020760  0.018938  0.023488   
15  0.038782  0.022740  0.053748  0.032784  0.023910  0.026165  0.023987   
16  0.035088  0.021293  0.029899  0.076390  0.034728  0.030013  0.028619   
17  0.045204  0.025347  0.149807  0.030683  0.022987  0.025586  0.026777   
18  0.036832  0.019571  0.121990  0.034316  0.024452  0.025074  0.025287   
19  0.025058  0.022578  0.058160  0.031938  0.032731  0.031680  0.024541   
20  0.036358  0.021602  0.035600  0.026769  0.026829  0.021610  0.023195   
21  0.033066  0.021917  0.073770  0.024795  0.023653  0.022338  0.020602   
22  0.030188  0.015932  0.059928  0.028772  0.020103  0.021001  0.022843   
23  0.024628  0.020082  0.019431  0.034690  0.025649  0.033322  0.028244   
24  0.025609  0.017521  0.027507  0.021475  0.019821  0.020962  0.018070   
25  0.035175  0.022619  0.029059  0.034911  0.022575  0.024449  0.025163   
26  0.033858  0.016167  0.027948  0.027826  0.037115  0.033019  0.027878   
27  0.023329  0.018851  0.468201  0.023400  0.020598  0.022980  0.023386   
28  0.029792  0.017583  0.312069  0.028452  0.021128  0.022230  0.019852   

      AAMP-M   AANAT-M    AAR2-M  ...  ZSWIM7-M  ZSWIM8-M    ZW10-M   ZWINT-M  \
0   0.024042  0.024596  0.028657  ...  0.041304  0.022708  0.022526  0.031664   
1   0.024706  0.021982  0.029938  ...  0.064079  0.019310  0.019493  0.038318   
2   0.024251  0.017034  0.016601  ...  0.045012  0.017111  0.019312  0.032742   
3   0.022987  0.020599  0.019450  ...  0.059958  0.017567  0.023987  0.034412   
4   0.024198  0.021429  0.027865  ...  0.078680  0.015795  0.020623  0.035171   
5   0.029035  0.024305  0.014334  ...  0.076644  0.019317  0.022338  0.039114   
6   0.023811  0.020788  0.016552  ...  0.047215  0.016792  0.022037  0.030985   
7   0.024157  0.019300  0.019626  ...  0.055558  0.018560  0.018914  0.035771   
8   0.021389  0.018395  0.016671  ...  0.043577  0.013839  0.017720  0.030853   
9   0.022140  0.020359  0.019158  ...  0.066336  0.019058  0.023817  0.040214   
10  0.022695  0.025897  0.026558  ...  0.045010  0.017810  0.027443  0.027736   
11  0.026384  0.021837  0.018806  ...  0.048387  0.016792  0.023258  0.035888   
12  0.024647  0.022043  0.022292  ...  0.062805  0.016720  0.023837  0.030709   
13  0.024961  0.023509  0.026430  ...  0.069800  0.017848  0.024963  0.030404   
14  0.020284  0.015672  0.014793  ...  0.066908  0.015322  0.021015  0.028390   
15  0.028101  0.022225  0.021864  ...  0.058173  0.014560  0.022520  0.028825   
16  0.028134  0.021457  0.018497  ...  0.060952  0.018681  0.026286  0.053717   
17  0.027806  0.027719  0.034502  ...  0.067582  0.021383  0.023877  0.042046   
18  0.026112  0.024170  0.024592  ...  0.049266  0.017237  0.021308  0.037779   
19  0.027056  0.020566  0.013688  ...  0.110624  0.018786  0.032108  0.049558   
20  0.030413  0.023099  

PCA transformation of the data

In [52]:
data_test_39=pca_39.transform(data_test3)

Get predictions

In [53]:
y_pred_39=best_random_39.predict(data_test_39)

In [54]:
y_pred_39

array(['C', 'NC', 'C', 'C', 'NC', 'NC', 'C', 'C', 'C', 'C', 'C', 'NC',
       'NC', 'C', 'C', 'C', 'C', 'C', 'NC', 'C', 'C', 'C', 'C', 'C', 'NC',
       'C', 'C', 'C', 'C'], dtype=object)

Read the test labels into pandas dataframe

In [55]:
y_test = pd.read_csv("/home/seeraja/anaconda3/iitgn/datasets-master/cancer subtype classification datasetspart01/head_neck_2/methylation/methyl_y_test.csv", low_memory=False)

In [56]:
y_test

Unnamed: 0   0
0            0   C
1            1  NC
2            2   C
3            3   C
4            4  NC
5            5  NC
6            6   C
7            7   C
8            8   C
9            9   C
10          10   C
11          11  NC
12          12  NC
13          13   C
14          14   C
15          15  NC
16          16   C
17          17   C
18          18  NC
19          19   C
20          20   C
21          21   C
22          22   C
23          23   C
24          24  NC
25          25   C
26          26   C
27          27   C
28          28   C

Convert to numpy array

In [57]:
arr_y_test=y_test.values
arr_y_test[:,1]

array(['C', 'NC', 'C', 'C', 'NC', 'NC', 'C', 'C', 'C', 'C', 'C', 'NC',
       'NC', 'C', 'C', 'NC', 'C', 'C', 'NC', 'C', 'C', 'C', 'C', 'C',
       'NC', 'C', 'C', 'C', 'C'], dtype=object)

In [58]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

Calculate the accuracy score

In [59]:
accuracy_score(arr_y_test[:,1], y_pred_39)

0.9655172413793104

Confusion matrix

In [60]:
cm = confusion_matrix(arr_y_test[:,1], y_pred_39)
print(cm)

[[21  0]
 [ 1  7]]


Calculate the probability values for each prediction 

In [61]:
prob_values=best_random_39.predict_proba(data_test_39)

In [62]:
prob_values

array([[0.86333333, 0.13666667],
       [0.07      , 0.93      ],
       [0.95666667, 0.04333333],
       [0.855     , 0.145     ],
       [0.035     , 0.965     ],
       [0.17666667, 0.82333333],
       [0.89666667, 0.10333333],
       [0.95333333, 0.04666667],
       [0.96833333, 0.03166667],
       [0.79833333, 0.20166667],
       [0.87      , 0.13      ],
       [0.        , 1.        ],
       [0.        , 1.        ],
       [0.95      , 0.05      ],
       [1.        , 0.        ],
       [0.69166667, 0.30833333],
       [0.9       , 0.1       ],
       [0.945     , 0.055     ],
       [0.01      , 0.99      ],
       [0.93833333, 0.06166667],
       [0.95333333, 0.04666667],
       [0.72      , 0.28      ],
       [0.95      , 0.05      ],
       [0.92666667, 0.07333333],
       [0.00666667, 0.99333333],
       [0.68666667, 0.31333333],
       [0.86666667, 0.13333333],
       [0.67833333, 0.32166667],
       [0.91833333, 0.08166667]])

Put the probability values in a dataframe and save to a csv file for further analysis

In [63]:
df=pd.DataFrame(prob_values)

In [64]:
df.to_csv("methyl_pca39_prob_values.csv")